import { Breadcrumb } from '@/components/layout/Breadcrumb';
import { useSEO } from '@/hooks/use-seo';

export default function Disclaimer() {
  useSEO({
    title: 'Disclaimer — GlobalTax',
    description: 'GlobalTax disclaimer. Our calculators provide estimates for informational purposes only — not financial or legal advice. Always verify with your tax authority.',
    canonical: 'https://taxnova.com/disclaimer',
  });
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-[680px] mx-auto px-4 py-12">
        <Breadcrumb items={[{ name: 'Home', url: '/' }, { name: 'Disclaimer', url: '/disclaimer' }]} />
        <h1 className="text-3xl font-bold text-[#0f172a] mb-6">Disclaimer</h1>
        <div className="text-[#334155] leading-relaxed space-y-4">
          <p className="font-medium text-[#0f172a]">Last updated: January 2025</p>
          <p>
            The information and calculators provided on GlobalTax are for general informational and educational purposes only. They do not constitute financial, legal, or tax advice.
          </p>
          <h2 className="text-xl font-bold text-[#0f172a] mt-6 mb-2">No Professional Advice</h2>
          <p>
            GlobalTax is not a licensed financial advisor, accountant, or tax professional. The results generated by our calculators are estimates based on publicly available tax rates and standard assumptions. They may not reflect your actual tax liability, which depends on your specific circumstances.
          </p>
          <h2 className="text-xl font-bold text-[#0f172a] mt-6 mb-2">Accuracy</h2>
          <p>
            While we make every effort to ensure our tax rates and formulas are accurate and up to date, tax laws change frequently. We cannot guarantee that all information is current or error-free. Always verify tax information with the relevant national tax authority: HMRC (UK), IRS (USA), CRA (Canada), ATO (Australia), or Finanzamt (Germany).
          </p>
          <h2 className="text-xl font-bold text-[#0f172a] mt-6 mb-2">Limitations</h2>
          <p>
            Our calculators use standard assumptions appropriate for most employed workers. They do not account for pension contributions, student loans, Scotland-specific rates, state/provincial taxes, rental income, self-employment income complexity, benefits-in-kind, or other individual circumstances that may affect your tax position.
          </p>
          <h2 className="text-xl font-bold text-[#0f172a] mt-6 mb-2">Consult a Professional</h2>
          <p>
            For advice on your specific tax situation, please consult a qualified tax advisor, chartered accountant, or other licensed financial professional in your jurisdiction.
          </p>
        </div>
      </div>
    </div>
  );
}
